version: "3.5"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./docker/database:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    container_name: app
    build: .
    volumes:
    - .:/app
    - ./data/api/bundle:/usr/local/bundle
    ports:
    - "3000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER_NAME: root
      DATABASE_USER_PASSWORD: root
